dateModified: 1637610861
email:
  fromEmail: admin@dev.com
  fromName: 'Craft Vue js'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5cb3d4ef-c06b-4a8c-9545-ec97609f0c23: TextAndImage # TextAndImage
    6b4d095a-f1a1-4726-ad03-9d41429d34ee: 'Craft Vue js' # Craft Vue js
    8d591ee8-4623-40cd-8f29-80ea85587347: Init # Init
    9db46ed5-608d-483d-b611-0d6a0d24553e: Home # Home
    36e7dd32-e013-4b60-9790-dd47b98630b8: components # components
    469b94cb-0c05-4b9f-a69d-367154f84cf8: 'Craft Vue js' # Craft Vue js
    c69d50f9-af27-4b15-9582-f02b8ae0f2b6: Common # Common
    e627f988-2849-4617-83ba-2e8ee7e3d46a: Title # Title
    eb2a58f7-043d-4b4c-be39-6fb99ff14066: Text # Text
    feaa025c-e24b-41d0-8886-38608c16eb0f: Home # Home
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-toolbox:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: /assets/
      publicPath: web
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Vue js'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
